### ISSUE TITLE
Build on Mac OS

### ISSUE THREAD

**Issue by K4stor** [EvergineTeam/Samples-2.5#3]
Hi I can"t build the samples on mac os, 

here goes a screenshot of the actual error.
![screen shot 2015-01-25 at 20 48 54](https://cloud.githubusercontent.com/assets/1078043/5892973/dc4d437a-a4d3-11e4-9502-5b80b8ba5d91.png)

**Comment by MarcosCobena** [comment]
Would you mind posting this issue on forum.waveengine.net? Thanks in advance

**Comment by JacobMillward** [comment]
I have this same issue with building any of the samples on OSX.

**Comment by MrStevns** [comment]
I know this is old but... the reason you can't build any of the samples on OS X is because they're made for windows. All the projects only compiles exe, therefore you either have to use the project converter which requires a PC.. or you can make a new project for the sample you want to try and setup all the files, then it should work. I've done it just now with the TiledMap example and it works.

**Comment by mgomar** [comment]
Hi there, we have a forum were we can solve your doubts/problems, please redirect to https://forum.waveengine.net/

**Comment by pulimento** [comment]
Hello there, 
We're focusing our support on [the forum](https://forum.waveengine.net) . Please post questions there. I'm closing this issue now due to inactivity.
